version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - .env.backend
    command: sh -c "node seed.js && npm start"
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    env_file:
      - .env.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  admin:
    build: ./admin
    ports:
      - "3001:80"
    env_file:
      - .env.admin
    depends_on:
      - backend

volumes:
  mongo_data: